name: Python Package Release

on:
  release:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-init.txt
        pip install -r requirements.txt
    - name: Release
      env:
        TWINE_CERT: ${{ secrets.TWINE_CERT }}
      run: |
        inv release.new
